spring:
  application:
    name: account-service

server:
  port: 8587
logging:
  level:
    root: INFO
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/