package com.altess.AccountMS.constants;

public interface ErrorMessage {
    String INVALID_FIRST_NAME = "Error304:Please enter your First Name";
    String INVALID_LAST_NAME = "Error305:Please enter your Last Name.";
    String INVALID_EMAIL_ID = "Error400:The email you entered is already on file and cannot be used for a new account. Please enter a different email address, or click forgot password to reset your password.";
    String ENTERED_INVALID_FIRST_NAME = "Error318:Entered first name is invalid. Please try again.";
    String ENTERED_INVALID_LAST_NAME = "Error320:Entered last name is invalid. Please try again.";
    String USER_NOT_REGISTERED = "Error5013:Looks like the email provided is not registered with us, please <a href=\"\\register\"><u>Register here</u></a>";
    String INVALID_CREDENTIALS = "Error317:We are sorry, that email-password combination was not found.&nbsp; Check your password and try again.&nbsp; If not, try the 'Forgot Password?' link below.&nbsp;&nbsp;";
    String MAX_ATTEMPTS_EXCEED = "ERROR5011:Too many attempts from non registered email, You have been blocked temporarily for 30 Minutes, Please contact Customer Service @ 1 (800) 432-8579 for assistance or <a href=\"/content/message\"> submit complaint </a>";
    String ACCOUNT_LOCKED = "Error317:We are sorry, that email-password combination was not found.&nbsp; Check your password and try again.&nbsp; If not, try the 'Forgot Password?' link below.&nbsp;&nbsp;";
    String FORGOT_PASSWORD_EMAIL_NOT_FOUND = "Error6001:This email address is not on file. Please enter a different email or click <a href=\"\\register\">here</a> to create a new account.";
    String USER_EMAIL_EXISTS = "Error331:The email address you have provided is associated with an active account. Please enter another email address or <strong><a href=\"/forgotPassword\">click here</a></strong> if you forgot your password.";
    String INVALID_FIRST_LAST_NAME = "Error321:Please enter your Name.";
    String INVALID_PASSWORD = "Invalid password";
    String INVALID_EMAIL_FORMAT = "Error600:We are sorry but we are unable to validate this email address.  Please try another valid email address.";
    String CONFIRM_INVALID_EMAIL_FORMAT = "Error600:We are sorry but we are unable to validate this confirm email address.  Please try another valid email address.";
    String SIGNIN_REQURIED = "Error550: Sign in required";
    String LOGIN_ID_REQURIED = "Error300:Please enter your email address as your Login ID";
    String INVALID_CONFIRM_EMAIL = "Error300:Please enter your confirm email address";
    String EMAIL_CONFIRMEMAIL_MISMATCH = "The email address and confirm email address entered do not match. Please try again.";
    String SLICK_EXCEPTION = "Slick Exception";
    String FORGOT_PASSWORD_EMAIL_REQUIRED = "Error700:Please enter your email address";
    String FORGOT_PASSWORD_URI_REQUIRED = "Forgot Password URI required";
    String INVALID_DOB = "Error701:Please enter valid date of birth";
    String INVALID_MOB = "Error702:Please enter valid date of month";
    String PASSWORD_FIELD_REQUIRED = "Error703:Please enter Password";
    String PASSWORD_LINK_EXPIRED = "Error704:Reset password link expired";
    String FRESH_ADDRESS_INACTIVE = "Error705:Fresh Address Exception";
    String USERID_REQUIRED = "Error706:Please enter userId";
    String FIRST_NAME_LENGTH_EXCEEDED = "Error707:firstname length should not be greater than 40 characters";
    String LAST_NAME_LENGTH_EXCEEDED = "Error708:lastname length should not be greater than 40 characters";
    String EMAIL_LENGTH_EXCEEDED = "Error709:email length should not be greater than 40 characters";
    String CONFIRM_EMAIL_LENGTH_EXCEEDED = "Error709:confirm email length should not be greater than 40 characters";
    String BU_INVALID_FIRST_NAME = "Error811:Please enter your first Name.";
    String BU_INVALID_MIDDLE_NAME = "Error812:Please enter your middle Name.";
    String BU_INVALID_LAST_NAME = "Error813:Please enter your last Name.";
    String BU_ENTERED_INVALID_FIRST_NAME = "Error814:Entered first name is invalid. Please try again.";
    String BU_ENTERED_INVALID_MIDDLE_NAME = "Error815:Entered middle name is invalid. Please try again.";
    String BU_ENTERED_INVALID_LAST_NAME = "Error816:Entered last name is invalid. Please try again.";
    String BU_INVALID_EMAIL = "Error817:Please enter your Email.";
    String BU_INVALID_EMAIL_FORMAT = "Error818:Unable to validate email, Please try another valid email address.";
    String BU_ENTERED_INVALID_USER = "Error819:Entered username is invalid. Please try again.";
    String BU_INVALID_USER = "Error820:Please enter your Username.";
    String BU_INVALID_TITLE = "Error821:Please enter Title.";
    String BU_ENTERED_INVALID_TITLE = "Error822:Entered Title is invalid. Please try again.";
    String BU_ENTERED_MOBILE_NUMBER = "Error823:Entered mobile number is invalid. Please try again.";
    String BU_PASSWORD_FIELD_REQUIRED = "Error824:Please enter Password";
    String BU_INVALID_PASSWORD_LINK = "Error825:Reset password link expired or Invalid link";
    String BU_INVALID_CREDENTIALS = "Please enter valid login credentials";
    String BU_USER_EMAIL_EXISTS = "Error827:user already exists with this email";
    String BU_MAX_ATTEMPTS_EXCEED = "Error828:Too many attempts from non registered email, You have been blocked temporarily for 30 Minutes";
    String BU_USER_NOT_REGISTERED = "Error829:Email provided is not registered";
    String ORDERID_REQUIRED = "Error710:Please enter orderId";
    String BU_INVALID_ROLE_IDS = "Error711:RoleIds are not valid";
    String BU_LENGTH_EXCEEDED = "Error830:length should not be greater than 80 characters";
    String BU_EXTERNAL_USER_NOT_FOUND = "Error318:Resource Not Found";
    String BU_USER_ID_NOT_FOUND = "Error831:userId Not Found";
    String BU_EXTERNAL_USER_EMAIL_EXISTS = "Error832: The";
}
