spring:
  application:
    name: product-service
  data:
    mongodb:
      database: altees
      authenticationDatabase: admin
      host: mongoDB
      port: 27017
server:
  port: 8585
logging:
  level:
    root: INFO
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:9000/eureka/