spring:
  application:
    name: product-service
  data:
    mongodb:
      database: altees
      authenticationDatabase: admin
      host: mongoDB
      port: 27017

  kafka:
    consumer:
      bootstrap-server: localhost:9092
      group-id: alteesGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8585
logging:
  level:
    root: INFO
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/