server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native



eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

